### ISSUE TITLE
Leave story does not trigger properly when leaving a section edition to home

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#134]
**Describe the bug**
Leave story does not trigger properly when leaving a section edition to home

**To Reproduce**
1. Enter a story, then a section (editor view)
2. Click on the fonio logo in nav menu
3. My little user icon is still displayed on the story card

**Expected behavior**
The story should be empty of users.

**Informations about your environment:**
 - OS: iOs
 - Browser: Chrome
 - Version: 22
 - Resolution: 1280x700

**Comment by mydu** [comment]
fixed by https://github.com/medialab/fonio/commit/e8b4fb413964ca0806f1bba304b0d3bf358aaa4d
