### ISSUE TITLE
delete resource won't delete coresponding assets in entityMap

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#135]
**Describe the bug**
delete resource won't delete corresponding assets in entityMap

**To Reproduce**
1. Go to 'section view'
2. Create a resource, then drag it to editor to create a contextualization
3. Delete the resource
4. Get 'SAVE_STORY_FAIL' error, validation story entity fail on server side

**Expected behavior**
delete resource should delete corresponding contextualization/contextualizer in section entityMap 

**Informations about your environment:**
 - Resolution [e.g. 1280x700]

**Additional context**
go check https://github.com/medialab/quinoa-server/blob/dev/src/validators/entityValidator.js for details

**Comment by robindemourat** [comment]
Closed by 604e48ed21d50dc3ead76e17776dd15bfc3b3da9
