### ISSUE TITLE
Docker : issue with routing when landing on specific page

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#147]
The routing seems to have issues when trying to land on a specific page in production (e.g. `/story/:storyId`)

# How to reproduce the bug

1. create a story or open an existing story
2. go to the "summary" view of the story
3. refresh the page

# Expected behaviour

The page should load to the summary of the story

# Actual behaviour

We get "404 Not Found - nginx"

**Comment by jri-sp** [comment]
fixed in a1980eefbb73bf9227e0a1ab47ab7b25c161b85d
