### ISSUE TITLE
hyperlink of webpage resource is not work

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#148]
**Describe the bug**
hyperlink contextualization of webpage resource is not work

**To Reproduce**
1. create a webpage resource 
2. drag it to editor to create a contextualization
3. click on hyperlink icon, it wont redirect to the corresponding website

**Expected behavior**
link should work

**Comment by mydu** [comment]
related to https://github.com/medialab/quinoa-story-player/issues/17

**Comment by robindemourat** [comment]
fixed by https://github.com/medialab/quinoa-story-player/commit/d413acac938459a910bf24ff21418830499ac7ee
