### ISSUE TITLE
In the password prompt, the read button can redirect to another story

### ISSUE THREAD

**Issue by mdamien** [medialab/fonio#177]
**Describe the bug**
The "read" button of the password prompt can redirect to the wrong text

**To Reproduce**
1. Go to the home page
2. Click on "open" of a story
3. In the password prompt, click on "read"

**Observed behavior**
I'm redirected to another story

**Expected behavior**
To read the story I've selected

**Screenshots**
[Here's a video](https://photos.google.com/share/AF1QipOfGCNDguqAfxsziMzJGEHyZdQ7O9rMgU6m9BKfJXU2UYeDd6Kn-kGCHKhDYxSXxA/photo/AF1QipMPrbLWz2MSmnlWmu1fbFH2bjNTujhdUHu-MDY?key=M3NjclJhWmhnNGRZVXI2MEI0Zm9PU1ZaYUxLd0Nn)

**Desktop (please complete the following information):**
 - OS: Xubuntu 16.10
 - Browser: Chrome
 - Version: 64

**Additional context**
It was on the PPRD server

**Comment by boogheta** [comment]
same story
