### ISSUE TITLE
Pictures orientation problem

### ISSUE THREAD

**Issue by diegantobass** [medialab/fonio#182]
When importing a picture the orientation is either reset or it was badly auto-guessed for the picture I imported.

**To Reproduce**

1. Go to library
2. Select import a picture
3. Drag the picture to the import section

**Observed behavior**
The orientation of my vertical picture was reset to horizontal

**Expected behavior**
The orientation of the picture should be set according to the EXIF data of the picture

**Screenshots**
![headshots 2018-08-01 at 10 36 10](https://user-images.githubusercontent.com/9825192/43511623-23f03a9a-9579-11e8-9be8-d8ec67824896.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.11
 - Browser: Firefox
 - Version: 61.0.1

**Additional context**
I didn't actualy try any other picture than the one because the internet is suddenly down at Sciences Po...

**Comment by robindemourat** [comment]
Thanks ! I have tried with some landscape pictures and could not manage to reproduce the bug, could you provide me with the image that caused this ?
