### ISSUE TITLE
Can't delete the very first footnote

### ISSUE THREAD

**Issue by paulgirard** [medialab/fonio#183]
**Describe the bug**
Delete a footnote from the trash bin icon on the foot note does clear the foot note content but don't delete the foot note itself.

**To Reproduce**
1. edit a section with no footnote
1. add a footnote
2. add some content
3. click the trash bin icon

**Observed behavior**

The foot note editor component disapears (which is good) but the footnote sign in the text is still there.
Going bask to the story editor where the footnote sign is, opens the footnote editor with no content.
If i backspace the footnote sign, it disapears (which is good).

**The bug only appears when deleting the very first footnote of the section.**
If i add multiple footnotes and then start deleting them, the last deletion is correct.

**Expected behavior**
The foot note sign should disapear from text editor when deleted the very first footnote.

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Browser  Firefox
 - 61

**Comment by robindemourat** [comment]
Investigation : seems to be due to a too fast focus change that does not let editorState to be updated with new state. Trying a fix but keeping it open.
