### ISSUE TITLE
Cursor placed in wrong position to after dnd an inline item and then try to insert/delete inline text

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#192]
**Describe the bug**
Cursor placed in wrong position to after adding dnd an inline item and then try to insert/delete inline text

**To Reproduce**
1. Go to the editor
2. Write some text 
3. Insert an inline items(bibtex, glossary, webpage) by dnd
4. change cursor position with left/right key and try to  insert/delete the inline text

**Observed behavior**
The cursor not move to the right position, jump to the `endSelection` position after adding the inline asset

**Expected behavior**
Cursor should be updated to right poisition

**Screenshots**
![cursor-bug](https://user-images.githubusercontent.com/3991275/44530897-c9553800-a6ef-11e8-8717-7a25e7ca5840.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome, firefox

**Comment by mydu** [comment]
May related to #190 #191

**Comment by robindemourat** [comment]
Seems to be fixed
