### ISSUE TITLE
[read/export/design] Top left menu blinking when clicking on text title

### ISSUE THREAD

**Issue by boogheta** [medialab/fonio#202]
For instance here : http://fonio-pprd.medialab.sciences-po.fr/test/read/1bbaf050-56d4-4ccb-a919-ccfe46f91150

Click on the title "Firefox is the best" : the menu on the left blinks

![fonio-0](https://user-images.githubusercontent.com/1822297/44727017-50802280-aad9-11e8-84fc-0e858586260d.gif)

**Comment by robindemourat** [comment]
Seems to be fixed by last modifications.
