### ISSUE TITLE
[library] Images should be previewable via a thumbnail

### ISSUE THREAD

**Issue by boogheta** [medialab/fonio#207]
Currently they can appear in tooltips when hovering them, but it is not the most convenient way to explore and find the one image you previously uploaded and are currently looking for
A simple thumbnail, or transparent background image would be nice

Also, by the way, the current preview as tooltip is a bit disturbing due to its trasnparency, it appears weirdly on top of buttons in the library left bar menu in edition mode

**Comment by robindemourat** [comment]
fixed by acd183bc67bfac05bc0d2f1e72a4e9232aa7d881
