### ISSUE TITLE
Massive copy/paste of a text with hyperlinks: not working

### ISSUE THREAD

**Issue by christophesciencespo** [medialab/fonio#209]
When I copied/pasted in a section a text with hyperlinks - i.e. https://fr.wikipedia.org/wiki/Nicolas_Hulot) it didn't work: see the result in the screenshot - (I had to select a shorter excerpt of the webpage to see a result (text + links)

<img width="1280" alt="capture d ecran 2018-08-28 a 16 04 58" src="https://user-images.githubusercontent.com/2485306/44728202-24b26c00-aadc-11e8-9a7e-e9dfb715af6e.png">

**Comment by robindemourat** [comment]
improved by fb6ffb7fbe9644bc7a38c5df95089b4f1ef0179c, still crashing
