### ISSUE TITLE
[big copy paste] infinite scrolling of links section...

### ISSUE THREAD

**Issue by boogheta** [medialab/fonio#210]
I copy pasted within a chapter this long article includin its annotations at the bottom : https://www.monde-diplomatique.fr/2018/06/BELLAMY_FOSTER/58734

Example here by scrollong to the "bottom" http://fonio-pprd.medialab.sciences-po.fr/test/read/46d6520f-48ce-42d9-8e3b-15e1b9a31a3b

![fonio-3](https://user-images.githubusercontent.com/1822297/44728280-59262800-aadc-11e8-8ad6-31d2d86f4e72.gif)

**Comment by robindemourat** [comment]
Seems to be related to lists of lists (ul > ul > li)
