### ISSUE TITLE
[edit] The text editor sometimes crashes in firefox

### ISSUE THREAD

**Issue by boogheta** [medialab/fonio#211]
I don't really know how to reproduce unfortunately, but I encountered it multiple times under various forms:
- the cursor does not display where the text is actually entered
- when starting to type, the screen crashes and required refreshing the page

![fonio-2](https://user-images.githubusercontent.com/1822297/44728652-50822180-aadd-11e8-9e62-f30f53e9880c.gif)

**Comment by robindemourat** [comment]
Possibly related trace :

![capture d ecran 2018-09-03 a 11 56 19](https://user-images.githubusercontent.com/1876890/45030488-449dde80-b04c-11e8-9b95-662284f1d459.png)

**Comment by paulgirard** [comment]
```bash
DOMException: "Node was not found" bundle.js:1:3604108
s
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3604108
t
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3600751
L
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3606337
w
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3606038
batchedUpdates
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3615579
lt
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3566369
$t
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3572696
[Show/hide message details.] NotFoundError: Node was not found bundle.js:1
removeChild
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3636436
a
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3612248
commitDeletion
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3613793
t
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3600679
L
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3606337
w
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3606038
batchedUpdates
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3615579
lt
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3566369
$t
http://fonio-pprd.medialab.sciences-po.fr/test/build/bundle.js:1:3572696
$t self-hosted:1028:17 
```

![image](https://user-images.githubusercontent.com/193478/45361951-dd47d780-b5d3-11e8-9cb9-b2a02ab42e8d.png)

**Comment by robindemourat** [comment]
still reproducing with the following scenario :

1. open the "mention item" widget and choose an image (or any other block)
1. focus on the line after
1. start writing

result: firefox crashes

**Comment by robindemourat** [comment]
Fixed for most recurring cases (opening the mention widget, switching focus between editors), still reproduces sporadically
