### ISSUE TITLE
Export of A Story to publish it (HTML format): weird result

### ISSUE THREAD

**Issue by christophesciencespo** [medialab/fonio#213]
I tried to export the Story "Test Suppression" (html) and I got this:

<img width="1280" alt="capture d ecran 2018-08-28 a 16 17 28" src="https://user-images.githubusercontent.com/2485306/44729021-25e49880-aade-11e8-819a-3924ab59dd9f.png">

**Comment by robindemourat** [comment]
For backup here is the story causing this :

[Test Suppression (1) copie.txt](https://github.com/medialab/fonio/files/2332405/Test.Suppression.1.copie.txt)

**Comment by mydu** [comment]
**Investigation**: due to the embed code has` <script>` tag resulting a `SyntaxError: Unterminated string`
**Temporary solution**: remove `script` tag from embed html
