### ISSUE TITLE
[Stress test] - Batch deletion massive resources in library view crash the browser

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#223]
**Describe the bug**

**To Reproduce**
1. Create massive number of resources (more than 100, e.g. `Le-Monde-diplomatique-2018-08.json`)
2. Delete them all

**Observed behavior**
browser get frozen, crash and require to reload

**Desktop (please complete the following information):**
 - Browser: Chrome, firefox

**Comment by robindemourat** [comment]
9acd41e08a5338ec70e87056b682a864df35ba0e improved but does not solve

**Comment by robindemourat** [comment]
Seems to be fixed (tried with `Le-Monde-diplomatique-2018-08.json` and did not witness a crash)
