### ISSUE TITLE
Copy/paste from external website with image content would create an 'atomic' block rather than 'unstyled' entity

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#231]
**Describe the bug**
Copy/paste from external website with image content would create a` 'atomic' `block rather than `'unstyled'` entity

**To Reproduce**
1. Copy text with image from https://www.monde-diplomatique.fr/2018/06/BELLAMY_FOSTER/58734 to editor
2. Go to design preview

**Observed behavior**
text after the image is converted in an `atomic` block

**Expected behavior**
need to paste as `unstyled` block

**Screenshots**
![screenshot from 2018-08-28 17-43-36](https://user-images.githubusercontent.com/3991275/44734345-fc316e80-aae9-11e8-9a5b-7722f57ad8da.png)

**Comment by robindemourat** [comment]
solved by fb6ffb7fbe9644bc7a38c5df95089b4f1ef0179c
