### ISSUE TITLE
Routing error after long iddle

### ISSUE THREAD

**Issue by arnaudmolo** [medialab/fonio#256]
I have been able to see the ``Design`` page as an unlogged user. The the password modale showed up.

⚠I haven't been able to reproduce the bug yet.

1. Browser was on the ``Design`` page when I left it yesterday.
2. When I came back, I've been redirected to the ``Home``.
3. I clicked on the ``Edit`` button of the same story

I've been redirected to the ``Design`` page and the password modale poped up. When I clicked  the upper right close button, I was redirected to the ``Home``.

**Expected behavior**
The password modal should have poped on the ``Edit`` click action, before the routing. I shall not have seen the ``Design`` page, nor any other page.
Even if I was logged in, I should have been redirected to the ``/story/:id``, not the ``/story/:id/design`` one

**Desktop (please complete the following information):**
 - OS: Osx Mojave
 - Browser Firefox
 - Version 63.0.3

**Comment by robindemourat** [comment]
Closing because no more cases of this bug since fall 2019 release
