### ISSUE TITLE
Cannot change metadata of a story

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#263]
**Describe the bug**
Cannot change metadata of a story

**To Reproduce**
1. Create a story
1. In the story summary, click on "edit properties"
1. Click on "update" 

**Observed behavior**
An error is thrown

**Expected behavior**
It should save the new story metadata

**Screenshots**
<img width="1280" alt="capture d ecran 2019-01-14 a 14 55 22" src="https://user-images.githubusercontent.com/1876890/51116898-9d586180-180c-11e9-89fe-d9e1a6250745.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by mydu** [comment]
due to changed in  https://github.com/medialab/quinoa-schemas/commit/77c5f979dff5f4563d29b50c9813480947be2494#diff-e963776ee731abba131163241eef3657
