### ISSUE TITLE
Copy-pasting content with contextualization between editors fail

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#273]
**Describe the bug**
Fail to copy/paste content with contextualization

**To Reproduce**
1. Copy content containing a inline/block entity in a main section editor
2. Paste content to same section/note or other section editor

**Observed behavior**
Content flashes then disappears. 

**Expected behavior**
It should be copied.

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome

**Additional context**
Copied content is shown at first, then be removed

**Comment by robindemourat** [comment]
May be solved by 911bae980d432170c0a97c9b4c778b674ae81d37
