### ISSUE TITLE
Undo/redo on hyperlink/glossary creation not behave in right way

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#274]
**To Reproduce**
1. Add a glossary/hyperlink contextualization in editor
2. undo by hit cmd+z 

Other related scenario :
1. after undo achieve, redo by cmd + y 

**Observed behavior**
undo is not performed until second attempt, redo will result to plain text (loosing the contextualization)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox/chrome

**Comment by robindemourat** [comment]
This results in undoing the contextualization creation but the text input - which might be the will of user for some cases (especially when "tagging" an existing text with a glossary or link) : I think it's okay ! closing
