### ISSUE TITLE
Copy-pasting contents containing inline bibliographic citations to another editor fail to render citations

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#284]
**To Reproduce**

1. create a bib contextualization
1. copy it
1. paste it to another section editor

**Screenshots**
![image](https://user-images.githubusercontent.com/3991275/52555884-3b7b1f80-2deb-11e9-9b5d-1fd2d9502846.png)

**Comment by robindemourat** [comment]
checked. fixed.
