### ISSUE TITLE
Copy-pasting contextualization not create new asset id in entityMap

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#287]
**Describe the bug**
Copy-pasting contextualization not create new asset id in entityMap

**To Reproduce**

1. create a resource and add contextualization in editor
2. copy some content include the contextualization
3. paste it either same or different editor

**Observed behavior**
content copied but inside raw content,  copied entityMap asset id is linked to old contextualizationId

Fail the unit-test at https://github.com/medialab/fonio/blob/8b3a4b7b2a2933cab75382367e842d5e887a816a/src/helpers/clipboardUtils/pasteFromInside.spec.js#L134

**Comment by mydu** [comment]
## Copy-pasting note with contextualization not create new asset id in new note entityMap 

**Describe the bug**
Copy-pasting note with contextualization not create new asset id in new note entityMap 

**To Reproduce**
Steps to reproduce the behavior:

1. create a note in main editor
2. create a resource and add contextualization in note
3. copy the note
4. paste it either same or different editor

**Observed behavior**
content copied but inside raw content of note, copied entityMap asset id is linked to old contextualizationId

Fail the unit-test at https://github.com/medialab/fonio/blob/d46eb4812249d21b67d3b9f63afd443aef07027d/src/helpers/clipboardUtils/pasteFromInside.spec.js#L165

**Comment by robindemourat** [comment]
passing
