### ISSUE TITLE
[Vocabulary] drop the appellation "story/récit" for the objects being manipulated by students

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#311]
... because it suggests a "sequential" & "storytelling" understanding of what can be done with the application.

Candidates for replacement:

* document
* website/site web
* web dissertation/dissertation web
* production
* project/projet
* publication
* work/travail

@thomastari et @audreybaneyx  je voudrais bien avoir votre avis sur cette question terminologique si vous passez par là !

**Comment by thomastari** [comment]
Je ne suis pas un spécialiste de narration mais un récit doit pouvoir être
composite aussi non ?
A priori ça ne me choquait pas.

Le ven. 19 juil. 2019 à 14:53, Robin de Mourat <notifications@github.com> a
écrit :

**Comment by robindemourat** [comment]
Ok gardons comme ça !
