### ISSUE TITLE
Editor cursor lost in chrome

### ISSUE THREAD

**Issue by mydu** [medialab/fonio#81]
# How to reproduce
input with markup ("##, -"), hit the space key
reproduce on Chrome browser, firefox works fine
# Current behavior
cursor got lost, exit enter mode 
# Wanted behavior
cursor should still be active

**Comment by robindemourat** [comment]
This happens on a linux os with chrome.

Additionnal bug : markdown shortcuts do not work anymore afterwards.

**Comment by robindemourat** [comment]
Possible related react issue : https://github.com/facebook/react/issues/6998

**Comment by robindemourat** [comment]
Seems not to reproduce after having changed to react 16. Let's keep it open for now in order to see if it reproduces.
